### ISSUE TITLE
[S2T]distutils not work on python 3.10

### ISSUE THREAD

**Issue by hohohacn** [PaddlePaddle/PaddleSpeech#3545]
**Describe the bug**
Traceback (most recent call last):
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py", line 36, in <module>
    parser = default_argument_parser()
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/training/cli.py", line 76, in default_argument_parser
    type=distutils.util.strtobool,
AttributeError: module 'distutils' has no attribute 'util'

**To Reproduce**
on paddlepaddle==2.5, python 3.10
run: 
cd /home/aistudio/PaddleSpeech/examples/aishell/asr1
bash run.sh --stage 1 --stop_stage 1
see error.
**Expected behavior**
aishell asr exaple run.sh run normal

**Screenshots**
Traceback (most recent call last):
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py", line 36, in <module>
    parser = default_argument_parser()
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/training/cli.py", line 76, in default_argument_parser
    type=distutils.util.strtobool,
AttributeError: module 'distutils' has no attribute 'util'

**Environment (please complete the following information):**
 - OS: aistudio.baidu.com
 - GCC/G++ Version unknown
 - Python Version 3.10
 - PaddlePaddle Version 2.5
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Informationo [e.g. Tesla V100 16G
 - CUDA/CUDNN Version 11.2
 - MKL Version :unknown
- TensorRT Version: unknown

**Comment by qingjiaozyn** [comment]
将原始的import distutils 改成 from distutils.util import strtobool，
type=strtobool
即可
